name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - run: mkdir -p build/{linux,macos,windows}
      - run: env GOOS=linux GOARCH=amd64 go build -v -o build/urlmap-linux ./cmd/urlmap.go

      - run: env GOOS=darwin GOARCH=amd64 go build -v -o build/urlmap-macos ./cmd/urlmap.go

      - run: env GOOS=windows GOARCH=amd64 go build -v -o build/urlmap-windows ./cmd/urlmap.go

      - uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: build/

      - run: go test -v .
